### ISSUE TITLE
RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3

### ISSUE THREAD

**Issue by l00494446** [wjchaoGit/Group-Activity-Recognition#6]
I am using pytorch0.4.1. When I run
python train_collective_stage1.py
it outputs the following:

Traceback (most recent call last):
  File "/home/lzj/anaconda2/envs/torch041/Group-Activity-Recognition/scripts/train_collective_stage1.py", line 27, in <module>
    train_net(cfg)
  File "/home/lzj/anaconda2/envs/torch041/Group-Activity-Recognition/train_net.py", line 68, in train_net
    model=Basenet(cfg)
  File "/home/lzj/anaconda2/envs/torch041/Group-Activity-Recognition/base_model.py", line 163, in __init__
    self.backbone=MyInception_v3(transform_input=False,pretrained=True)
  File "/home/lzj/anaconda2/envs/torch041/Group-Activity-Recognition/backbone.py", line 11, in __init__
    inception=models.inception_v3(pretrained=pretrained)
  File "/home/lzj/anaconda2/envs/torch041/lib/python3.5/site-packages/torchvision/models/inception.py", line 26, in inception_v3
    model = Inception3(**kwargs)
  File "/home/lzj/anaconda2/envs/torch041/lib/python3.5/site-packages/torchvision/models/inception.py", line 65, in __init__
    m.weight.data.copy_(values)
RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3

What could be the reason of the problem? How to fix it?

**Comment by PHDPeter** [comment]
what is your pytorch version?

**Comment by l00494446** [comment]
pytorch0.4.1, python3.5, torchvision-0.1.8
now I changed the torchvision-0.2.1, python3.6, it works for me now. i think it maybe the Version issues of torchvision. 
thanks a lot.
